### ISSUE TITLE
Try using libpostal to parse location strings into structured data

### ISSUE THREAD

**Issue by jim** [City-Bureau/city-scrapers#208]
https://github.com/openvenues/libpostal

I haven't tested this yet, but hopefully we can use just before geocoding to improve our success rate.

cc @r-wei

**Comment by easherma** [comment]
I’ve used libpostal before so we can discuss this!

**Comment by jim** [comment]
@easherma Great! My thought is to add an additional middleware (`LocationStandarizationMiddleware` maybe) and insert it before the geocoding middleware. Inside this new middleware, we can use libpostal (through its Python bindings) to convert our grab-bag location strings into structured data.

One thing I notice is that libpostal returns its data in all lowercase (having to do with its internal machinations). We already have [inflector](https://pypi.python.org/pypi/Inflector) in the project so perhaps we can run the results through `titleize`, either in the middleware or at display time? I think that might be Good Enough.

**Comment by bonfirefan** [comment]
Do we want to use libpostal or usaddress for this? In the new pipeline plan it seems we were going with usaddress. Libpostal seems more applicable for multinational locations.

**Comment by r-wei** [comment]
I think libpostal is just another thing we could try. My 2 cents: See how it goes with usaddress. If we're not getting good results on enough of the items, try passing them through libpostal.

**Comment by easherma** [comment]
They are each made for separate purposes. Usaaddresses mainly attempts to
guess address components from a single input string (this isn’t super
helpful for geocoding, tbh, but it may help us clean our input). Libpostal
does that too, but it also generates trees of guesses of a standardized
address based on input.

So libpostal if given ‘123 S Stave St.’ would return a bunch of potential
options like ‘123 South Stave Street, 123 S Saint’ , and other example I
can’t quite make up off the top of my mind, especially cause I’m on mobile
atm. :-p

Basically you would use libpostal to generate tree if potential addresses
and geocode each one, then score the results by what would be most likely
to be what you were actually looking for.

If that sounds like a pain and a lot to implement, its because it is. :-p
Pelias/Mapzen used libpostal as part of its parsing which is one of the
reasons why I liked it. :-(

Cleaning and standardizing address data is kind if a pain most ways you
slice it. I suspect a combo of some basic cleaning/parsing + having a cache
of known entries that are somewhat manually tended to and verified will
probably strike the right balance, given each city is someone a limited
range and many meetings will be static.

**Comment by jim** [comment]
No need to move forward with this if we're going a different direction.
