### ISSUE TITLE
New Geocoding Pipeline Plan

### ISSUE THREAD

**Issue by jim** [City-Bureau/city-scrapers#249]
At the meeting tonight, we discussed how to proceed with the geocoding part of the application. We decided to follow up @easherma's idea to split the process into multiple pipelines, with the following steps and a pipeline for each:

- [ ] Address cleanup using [usaddress](https://github.com/datamade/usaddress) (@bonfirefan)
Spiders that are including city in addresses: Chicago City Council, Chicago Public Schools: School Actions, City College of Chicago, Chicago Police Department
- [ ] Look up clean address in local cache.
- [ ] If necessary, geocode cleaned address using MapBox API. (@easherma)
- [ ] If necessary, assign a community area using local GeoJSON data, python geocoder library or data portal data
- [ ] If necessary, write geocoded lat/long and community area to local cache

We will create individual PRs for each of these steps as they are picked up.

**Comment by jim** [comment]
This supersedes #207.

**Comment by jim** [comment]
cc @pjsier 😄

**Comment by r-wei** [comment]
Related to #208

**Comment by r-wei** [comment]
Reference for scrapy pipelines: https://www.youtube.com/watch?v=MtU4xuI8v4c&t=0s&list=PLyCZ96_3y5LXfPVZkHjhHRuIWhcjvCyQA&index=3

**Comment by easherma** [comment]
We can use the Python geocoder library to choose a provider that returns a neighborhood as well. We can later get lat lng, then reverse geocode to get a community area, or use the SODA api to do a point in polygon search, depending on the quality/needs of the output.

**Comment by easherma** [comment]
FYI, Mapbox terms: 
"The results from geocoding with the mapbox.places mode must be displayed on a Mapbox map and cannot be stored permanently. The mapbox.places-permanent mode, available with an Enterprise plan, does not have these licensing restrictions."

This isn't as bad as Google because we're much more likely to want to use Mapbox to display stuff. 

I think we can get around the permanent thing too, have some thoughts about that. I don't think its enough to not proceed, but wanted to drop this as a note when I noticed it.

**Comment by eads** [comment]
Mapbox also has a quasi-editorial team and might be willing to grant an exception to the terms for journalistic purposes. I can make the hook up if that's useful.

**Comment by easherma** [comment]
@eads I was thinking the same thing, I have several contacts at Mapbox as well (including one who actually works remotely here in Chicago! )

**Comment by easherma** [comment]
We're going to write a separate pipeline/method for writing cached results to Airtable or others

**Comment by easherma** [comment]
We also will have a pipeline to check for cached results

**Comment by easherma** [comment]
Following up on last night, I want to clarify a few aspects (which I also discussed [here](https://github.com/City-Bureau/city-scrapers/issues/208#issuecomment-372705251):

- [ ] Address cleanup using usaddress (@bonfirefan)
usaddress is only going to be of limited assistance cleaning address data. As [their docs](https://github.com/datamade/usaddress) say:
"**What this cannot do:** It cannot identify address components with perfect accuracy, nor can it verify that a given address is correct/valid."

**This is going to be a lot to bite off**, especially programmatically. It probably deserves it's own issue so we can break down what specifically we want to do to address data and prioritize. It is very hard to know what address a user _meant_ by what they entered. If we get a result back from a geocoder, it is similarly challenging to _prove_ that that result is actually what we wanted. We have to know a lot of real-world information in order to verify that.

Libpostal is a more useful tool for programatically standardizing/normalizing address input, if we want to get serious about it. 

This is a big topic, but here is some reading if you're curious:
https://www.mjt.me.uk/posts/falsehoods-programmers-believe-about-addresses/
https://mapzen.com/blog/inside-libpostal/
http://www.intermap.com/risks-of-hazard-blog/geocoding-101

Luckily, our geographic scopes are relatively small. A single city is more manageable, and we can deal with tricky address issues more meaningfully for two main reasons:

1. We live here
2. We have documenters that are physically _going_to these places, and can tell us if we gave them the right info or not! ( this is a huuuge advantage! )

- [ ]  Look up clean address in local cache.
Different geocoders may parse and have address labels using slightly different structures, so these may not be perfect matches. We can test this given a dump of our current cache. It shouldn't be too much of a headache. 
- [x]  If necessary, geocode cleaned address using MapBox API. (@easherma)
This works. Open to code review/thoughts/feedback. 
- [ ]  If necessary, assign a community area using local GeoJSON data, python geocoder library or data portal data
Many geocoders, Mapbox included, return neighborhood data. We just need to decide where/how to store that context. As is, the location_url at least allows us to call that same query again to fetch additional metadata if we'd like. Either way, I kind of like is as a separate step anyways, given the above challenges (as in we may want to flesh this part of the process out and involve some human eyeballs looking at the meeting locations before including it on assignments). 
- [ ]  If necessary, write geocoded lat/long and community area to local cache
I suggest having a process in place/way to flag whether a given result is accepted as is or verified by a human as correct. 

At some point it would be good to touch base with @diaholliday about the current flow for assigning meetings to documenters and how the follow-up/de-brief process works. 

For example, assuming we send someone on an assignment and than collect their report, one of the things we can do is ask them if the address and location we provided to them was accurate or not, and if there were any other tricky things to know about getting to the location. 

This can be cross-referenced to our cache, and gives us a growing body of verified locations (since I suspect many meetings happen in the same place often enough) along with extra info about how to get there that we can provide (such as 'entrance is on the north side of the building and you have to take the elevator', just to make something up). 

Phew, this turned out longer than I intended!

**Comment by eads** [comment]
Re the collecting the reporting, that's something I wondered from the very beginning. It would be pretty nice to be able to capture that data from documenters and have it override or at least have some priority over whatever we're getting from the scrapers. "It says 5th floor, but it's actually been on the 6th floor for past three months" or whatever.

**Comment by diaholliday** [comment]
Big yes to @eads's point here^

**Comment by easherma** [comment]
Still thinking about this, and still leaning towards address validation as part of the process of reviewing a scraped spider (perhaps through a form or other process as has been discussed a bit). 

Also dropping this link here so I don't lose it: 
https://www.usps.com/business/web-tools-apis/welcome.htm

**Comment by bonfirefan** [comment]
Hey @easherma, can you expand on that idea a bit? I remember we discussed this last coding session, but you appear to be describing something that would be served well within a pipeline. Or do you mean that we would want to modify each spider to validate addresses while parsing? Intrigued by the USPS API, also.

**Comment by easherma** [comment]
@bonfirefan Sure thing, apologies for being vague. 

There are a couple different steps that would typically be involved in cleaning up address data. If these  would be done, it would usually be prior to geocoding in order to help increase the usability and accuracy of the geocoding results. These steps can be considered optional, though clearly there is a good  chance of upping the accuracy of our geocoding results:

- Parsing
    - At the moment,  we are doing this twice. Once with usaaddress, and then again with Mapbox (most if not all geocoders do this as part of their process).  
- Standardization/Normalization
   - This  is a bit of what we've talked about implementing further. This involves directly manipulating and  changing the original scraped data.
- Verification
    - This is what something like  the  USPS would be useful for, ensuring that the generated address  conforms to and matches an actual address.

Many geocoders often side-step the last two for a variety of reasons. They often  get around it  by having the user select a valid entry via  some sort of autocomplete. Mapbox and Google also do interpolation, so if they can't find an address they will just make up an approximation. 

Either way, trying to normalize address data does open a whole can of worms. While I'm not opposed to it completely,  I'm concerned about the technical debt we'd be committing to taking on (especially with a volunteer project) if we try to shoulder this responsibility ourselves. Just hoping to make an intentional choice here. :-) 

Because of this I'm also growing wary about including it directly in the scraping pipeline. I think the extra complexity it introduces is going to be  confusing  for devs trying to jump in and not concern themselves with geocoding, and puts us at risk of violating separation of concerns (e.g. scrapers should scrape, geocoders should geocode). 

If the main goal is getting and providing useful location info for documenters and/or mapping the 
locations of these meetings, there could be a couple ways to achieve that goal(having a user or admin verify meeting locations via a form or some other interface being one example that comes to mind), which is at least a little of what I think @eads was getting at. 

Hope that helps!

**Comment by pjsier** [comment]
Closed by #487
