### ISSUE TITLE
Spider: Illinois Procurement Policy Board

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#806]
URL: https://www2.illinois.gov/sites/ppb/Pages/future_board_minutes.aspx
Doc URL: https://www2.illinois.gov/sites/ppb/Pages/board_minutes.aspx
Spider Name: `il_procurement_policy`
Agency Name: Illinois Procurement Policy Board

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by jingwu21** [comment]
Is this up for grabs? If so I would like to give it a go.

**Comment by pjsier** [comment]
@jingwu21 all yours if you're interested!

**Comment by jingwu21** [comment]
In the url: https://www2.illinois.gov/sites/ppb/Pages/future_board_minutes.aspx it has a pdf. Do I just scrape the texts?

**Comment by pjsier** [comment]
The doc URL is an additional page we'll want to scrape to get past minutes. Since they don't seem to overlap, you should be able to include both in `start_urls` and implement different parsing logic to pull meetings

**Comment by jingwu21** [comment]
Ok. Thank you.

**Comment by jingwu21** [comment]
I am implementing the test cases for my spider but when I run pytest I get errors saying "IndexError: list index out of range".  `test_response = file_response(
    join(dirname(__file__), "files", "il_procurement_policy.html"),
    url="https://www2.illinois.gov/sites/ppb/Pages/future_board_minutes.aspx",
)
spider = IlProcurementPolicySpider()

freezer = freeze_time("2019-10-07")
freezer.start()

parsed_items = [item for item in spider.parse(test_response)]`

The error originates from my parsed_items. But I am not sure why it is empty since when I run "scrapy crawl myfile.py" it actually gives me the meetings.

**Comment by pjsier** [comment]
It might be worth double-checking what's in the HTML file or possible regenerating it from what you're seeing at that URL currently to be sure that the right output is in there

**Comment by jingwu21** [comment]
Thank you. I manage to get the errors down to 3.

**Comment by pjsier** [comment]
Closed by #925, thanks @jingwu21!
