### ISSUE TITLE
CANCELED Meetings are not recognized by get_status function

### ISSUE THREAD

**Issue by sameerchandra** [City-Bureau/city-scrapers#831]
If the word 'canceled' is there in the meeting title, get_status() wouldn't recognize the meeting as Canceled

**Comment by pjsier** [comment]
@sameerchandra do you have a specific example of this not working? We're checking for this in the `_get_status` function currently

https://github.com/City-Bureau/city-scrapers-core/blob/e3dd19e800697a819b7fd7104b24202e9a2dcdea/city_scrapers_core/spiders/spider.py#L45-L57

**Comment by sameerchandra** [comment]
Hi @pjsier If you check this [link](https://www.isp.state.il.us/media/openmtgs.cfm), the title of the meeting contains CANCELED but `_get_status` doesn't identify the meeting as cancelled because it is only searching for the world cancel

**Comment by pjsier** [comment]
The issue here isn't that it's not finding the substring "cancel" which should match "cancelled" or "canceled", it's that the title being passed to the function in the PR (https://github.com/City-Bureau/city-scrapers/pull/830/files#diff-5599fb5b1bde4d2a5559d9c482ddbe6aR44) isn't actually including "CANCELED" in the `title` property of the meeting.

The way to address this in the `_get_status` method is to pass an additional `text` kwarg that includes any text that should be checked for cancellation words outside of what's included in the meeting item. You can see an example of this in [`il_lottery`](https://github.com/City-Bureau/city-scrapers/blob/85426c5d88e817abd045e86c8d8faaddfdecb068/city_scrapers/spiders/il_lottery.py#L59) where the full parsed text of an item is passed as the `text` kwarg because it might contain the text "canceled" or "rescheduled" but we don't want to include that in the title. I'm closing this for now, but happy to answer more questions here
